# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import qdarkstyle
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 210, 261, 61))
        self.pushButton.setMinimumSize(QtCore.QSize(5, 5))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "font: 22pt \"黑体\";\n"
                                      "background-color: rgb(0, 0, 0);\n"
                                      "")
        self.pushButton.setAutoRepeatDelay(600)
        self.pushButton.setAutoRepeatInterval(200)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))


class Methods(QtWidgets.QMainWindow, Ui_Dialog):
    def __init__(self):
        super(Methods, self).__init__()

        self.setupUi(self)

app = QtWidgets.QApplication(sys.argv)
app.setStyleSheet(qdarkstyle.load_stylesheet())
window = Methods()
window.show()
sys.exit(app.exec_())
